### ISSUE TITLE
missing /packages/core_elements/src/web-animations-js/web-animations-next-lite.min.js.map

### ISSUE THREAD

**Issue by SatWiz** [dart-lang/polymer-dart#54]
When using <paper-dropdown-menu> I am having this error:
[web] GET /packages/core_elements/src/web-animations-js/web-animations-next-lite.min.js.map => Could not find asset core_elements|lib/src/web-animations-js/web-animations-next-lite.min.js.map.

If I copy the missing file from the JS repository to the dart package dir it is not working. Where should I copy the missing file or how can it fixed?
Thanks.

**Comment by SatWiz** [comment]
I get the error when using the paper-dropdown-menu

**Comment by jakemac53** [comment]
Can you make sure you are on the most recent version? I think this has been fixed, but I could be wrong.

**Comment by SatWiz** [comment]
I am using polymer 0.16.1+2, core_elements 0.7.0, paper_elements 0.7.0.
Did a pub cache rebuild. 

The funny thing is when I run the build project from my server, that missing file is not called.
It only appears when run as javascript from my Dart editor.
Any clues?

**Comment by sigmundch** [comment]
@jakemac53 it might be that we are not be publishing the .map files in the pub package because we have a .gitignore in the core_elements repo that excludes all map files.

We could add them back, or we could remove the [`// #sourcemapurl` line](https://github.com/dart-lang/core-elements/blob/master/lib/src/web-animations-js/web-animations-next-lite.min.js#L17) in the minified .js file so that browsers don't try to fetch the map file (most users don't need the source-map support for these files).

@SatWiz do you currently need to debug this script, or you just happen upon this error message? If you happen upon it, I believe that the error you see is benign and can be ignored until we get this sorted out (it shouldn't affect other parts of your app).

**Comment by SatWiz** [comment]
Nope, I don't need to debug. Just report the bug ;). Thanks for remind me what map files are. Now I guess to understand why the error don't appears when run from the server. 
Still don't understand when run the file locally from the computer I get the error though.
